Repository TeamDearToday/Deartoday-Android, pull requests merged in 2022-07, with the labels that each got.

#3 [CHORE] Project 기초 설정
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/co/kr/deartoday/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/deartoday/application/DeartodayApplication.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/base/BaseActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/base/BaseFragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/main/MainActivity.kt
  app/src/main/java/co/kr/deartoday/util/DeartodayDefaultLifecycleObserver.kt
  app/src/main/java/co/kr/deartoday/util/PresentationExtensions.kt
  app/src/main/java/co/kr/deartoday/util/SingleLiveEvent.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/font/pretendard_black.otf
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_extrabold.otf
  app/src/main/res/font/pretendard_extralight.otf
  app/src/main/res/font/pretendard_light.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
  app/src/main/res/font/pretendard_thin.otf
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/co/kr/deartoday/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: chore 🏗, 승현 🛵

#5 [DOCS] README.md 수정
  README.md
Labels: docs 📝, 승현 🛵

#9 [CHORE] 앱 기본 정보 설정
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
Labels: chore 🏗, 승현 🛵

#12 [CHORE] Dear today Style Guide 적용
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/font/gmarket_sans_bold.otf
  app/src/main/res/font/gmarket_sans_light.otf
  app/src/main/res/font/gmarket_sans_medium.otf
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: design 🎨, chore 🏗, 승현 🛵

#13 [FIX] Build 시 생기는 error 해결
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: bug 🐛, 승현 🛵

#15 [FEATURE] 홈 UI 구현 (홈 ViewPager2 하단 indicator 구현)
  app/src/main/java/co/kr/deartoday/presentation/ui/main/MainActivity.kt
  app/src/main/res/drawable/circle_border.xml
  app/src/main/res/drawable/circle_full.xml
  app/src/main/res/layout/activity_main.xml
Labels: feature 🚀, design 🎨, 승현 🛵

#18 [FEATURE] 홈 UI 구현 (오늘 날짜 표시, 홈 아이콘 추가)
  app/src/main/java/co/kr/deartoday/presentation/ui/main/MainActivity.kt
  app/src/main/res/drawable/ic_help.xml
  app/src/main/res/drawable/ic_setting.xml
  app/src/main/res/drawable/rectangle_light_blue_radius_4.xml
  app/src/main/res/layout/activity_main.xml
Labels: feature 🚀, design 🎨, 승현 🛵

#16 [FEATURE] Social Singin UI 구현 / Kakao SDK, API 환경 세팅 / 토큰 발급
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/deartoday/application/DeartodayApplication.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/signin/SignInActivity.kt
  app/src/main/res/drawable-hdpi/signin_ic_kakao.png
  app/src/main/res/drawable-hdpi/signin_logo.png
  app/src/main/res/drawable-mdpi/signin_ic_kakao.png
  app/src/main/res/drawable-mdpi/signin_logo.png
  app/src/main/res/drawable-xhdpi/signin_ic_kakao.png
  app/src/main/res/drawable-xhdpi/signin_logo.png
  app/src/main/res/drawable-xxhdpi/signin_ic_kakao.png
  app/src/main/res/drawable-xxhdpi/signin_logo.png
  app/src/main/res/drawable-xxxhdpi/signin_ic_kakao.png
  app/src/main/res/drawable-xxxhdpi/signin_logo.png
  app/src/main/res/drawable/rectangle_yellow_radius_2.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/values/strings.xml
  settings.gradle
Labels: feature 🚀, design 🎨, 우형 🍩

#22 [FIX] MainActivity error
  app/src/main/res/drawable/rectangle_light_blue_radius_4.xml
Labels: bug 🐛, 승현 🛵

#25 [FEATURE] AnimatorUtil 구현
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding1Fragment.kt
  app/src/main/java/co/kr/deartoday/util/AnimationUtil.kt
  app/src/main/res/layout/fragment_onboarding1.xml
Labels: feature 🚀, 승현 🛵

#27 [FEATURE] Onboarding Animation 구현
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding11Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding1Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding2Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding4Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding5Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding6Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding7Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding8Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding9Fragment.kt
  app/src/main/res/drawable-hdpi/bg_letter.png
  app/src/main/res/drawable-mdpi/bg_letter.png
  app/src/main/res/drawable-xhdpi/bg_letter.png
  app/src/main/res/drawable-xxhdpi/bg_letter.png
  app/src/main/res/drawable-xxxhdpi/bg_letter.png
  app/src/main/res/drawable/ic_bg_letter.xml
  app/src/main/res/layout/fragment_onboarding1.xml
  app/src/main/res/layout/fragment_onboarding11.xml
  app/src/main/res/layout/fragment_onboarding2.xml
  app/src/main/res/layout/fragment_onboarding4.xml
  app/src/main/res/layout/fragment_onboarding5.xml
  app/src/main/res/layout/fragment_onboarding6.xml
  app/src/main/res/layout/fragment_onboarding7.xml
  app/src/main/res/layout/fragment_onboarding8.xml
  app/src/main/res/layout/fragment_onboarding9.xml
  app/src/main/res/values/strings.xml
Labels: feature 🚀, design 🎨, 유리 ☁️

#29 [CHORE] Onboarding Animation 구현
  app/src/main/res/layout/fragment_onboarding11.xml
  app/src/main/res/layout/fragment_onboarding2.xml
  app/src/main/res/layout/fragment_onboarding4.xml
  app/src/main/res/layout/fragment_onboarding5.xml
  app/src/main/res/layout/fragment_onboarding6.xml
  app/src/main/res/layout/fragment_onboarding7.xml
  app/src/main/res/layout/fragment_onboarding8.xml
  app/src/main/res/layout/fragment_onboarding9.xml
  app/src/main/res/values/strings.xml
Labels: design 🎨, chore 🏗, 유리 ☁️

#33 [FEATURE] Onboarding Back Button 막기
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/OnboardingActivity.kt
Labels: feature 🚀, 유리 ☁️

#39 [FEATURE] ItemDecoration 생성
  app/src/main/java/co/kr/deartoday/presentation/ui/messagebox/MessageBoxActivity.kt
Labels: feature 🚀, chore 🏗, 유리 ☁️

#37 [FEATURE] DearTodaySharedPreferences 구현
  app/src/main/java/co/kr/deartoday/data/sharedpreferences/DearTodaySharedPreferences.kt
Labels: feature 🚀, 우형 🍩

#49 [FEATURE] CustomDialogUtil 구현
  app/src/main/java/co/kr/deartoday/util/CustomDialogUtil.kt
  app/src/main/res/drawable/inset_horizontal_80.xml
  app/src/main/res/values/strings.xml
Labels: feature 🚀, 승현 🛵

#47 [FEATURE] Message Box 바뀐 뷰 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/deartoday/presentation/adapter/MessageBoxAdapter.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/messagebox/MessageBoxActivity.kt
  app/src/main/java/co/kr/deartoday/util/CustomDialogUtil.kt
  app/src/main/java/co/kr/deartoday/util/LineCalculation.kt
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/inset_horizontal_80.xml
  app/src/main/res/drawable/rectangle.xml
  app/src/main/res/layout/activity_message_box.xml
  app/src/main/res/layout/dialog_message_box.xml
  app/src/main/res/layout/item_message_box_list.xml
  app/src/main/res/values/strings.xml
Labels: feature 🚀, chore 🏗, 유리 ☁️

#54 [FEATURE] Message Box minHeight 지정
  app/src/main/java/co/kr/deartoday/presentation/ui/messagebox/MessageBoxActivity.kt
  app/src/main/res/layout/dialog_message_box.xml
Labels: feature 🚀, 유리 ☁️

#58 [CHORE] 주석 제거
  app/src/main/java/co/kr/deartoday/presentation/ui/messagebox/MessageBoxActivity.kt
Labels: chore 🏗, 유리 ☁️

#62 [FEATURE] 시간여행 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/deartoday/presentation/ui/base/BaseFragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineImagePickerFragment.kt
  app/src/main/java/co/kr/deartoday/presentation/viewmodel/TimeMachineViewModel.kt
  app/src/main/java/co/kr/deartoday/util/ContextUtil.kt
  app/src/main/res/drawable/rectangle_radius_8.xml
  app/src/main/res/drawable/rewind.xml
  app/src/main/res/layout/activity_time_machine.xml
  app/src/main/res/layout/fragment_time_machine_image_picker.xml
  app/src/main/res/values/themes.xml
Labels: feature 🚀, 승현 🛵

#63 [FIX] TimeMachineImagePickerFragment 상태 관리 오류
  app/src/main/res/drawable-hdpi/rewind.png
  app/src/main/res/drawable-mdpi/rewind.png
  app/src/main/res/drawable-xhdpi/rewind.png
  app/src/main/res/drawable-xxhdpi/rewind.png
  app/src/main/res/drawable-xxxhdpi/rewind.png
  app/src/main/res/drawable/rewind.xml
Labels: bug 🐛, 승현 🛵

#66 [FEATURE] 시간여행 관련 데이터 클래스 구현
  app/src/main/java/co/kr/deartoday/data/model/response/DetailTapeResponse.kt
  app/src/main/java/co/kr/deartoday/data/model/response/ResponseTimeTravelTape.kt
  app/src/main/java/co/kr/deartoday/data/model/response/TapesResponse.kt
  app/src/main/java/co/kr/deartoday/presentation/adapter/TapeAdapter.kt
Labels: feature 🚀, 우형 🍩

#68 [FIX] #67 - TimeTravelActivity fix
  app/src/main/java/co/kr/deartoday/presentation/ui/timetravel/TimeTravelActivity.kt
Labels: bug 🐛, 우형 🍩

#72 [FEATURE] 메인 - 메시지, 시간여행 확인 뷰 연결
  app/src/main/java/co/kr/deartoday/presentation/ui/main/MainRightFragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/messagebox/MessageBoxActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timetravel/TimeTravelActivity.kt
  app/src/main/res/values/strings.xml
Labels: feature 🚀, chore 🏗, 유리 ☁️

#78 [FEATURE] 과거 나와의 대화 방 1 UI 구현
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat1Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachinePastRoomFragment.kt
  app/src/main/res/drawable-hdpi/convo_bg_aos.png
  app/src/main/res/drawable-mdpi/convo_bg_aos.png
  app/src/main/res/drawable-xhdpi/convo_bg_aos.png
  app/src/main/res/drawable-xxhdpi/convo_bg_aos.png
  app/src/main/res/drawable-xxxhdpi/convo_bg_aos.png
  app/src/main/res/layout/fragment_time_machine_chat1.xml
Labels: feature 🚀, 승현 🛵

#81 [FEATURE] BaseFragment abstract 변수 값 할당
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat2Fragment.kt
Labels: feature 🚀, 승현 🛵

#88 [FEATURE] 시간 여행 상세보기 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/deartoday/presentation/ui/timetravel/TimeTravelDetailActivity.kt
  app/src/main/java/co/kr/deartoday/util/StickyScrollView.kt
  app/src/main/res/drawable-hdpi/rewind_disable.png
  app/src/main/res/drawable-mdpi/rewind_disable.png
  app/src/main/res/drawable-xhdpi/rewind_disable.png
  app/src/main/res/drawable-xxhdpi/rewind_disable.png
  app/src/main/res/drawable-xxxhdpi/rewind_disable.png
  app/src/main/res/drawable/rectangle_stroke_blue_radius_20.xml
  app/src/main/res/drawable/rectangle_yellow_radius_20.xml
  app/src/main/res/layout/activity_time_travel.xml
  app/src/main/res/layout/activity_time_travel_detail.xml
  app/src/main/res/layout/item_time_travel.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: bug 🐛, feature 🚀, 우형 🍩

#90 [FEATURE] 과거 나와의 대화 방 5 UI 구현
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat1Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat4Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/viewmodel/TimeMachineViewModel.kt
  app/src/main/res/drawable/rectangle_textfield_border_blue_radius_4_20.xml
  app/src/main/res/drawable/rectangle_textfield_border_yellow_radius_4_20.xml
  app/src/main/res/drawable/rectangle_textfield_radius_4_20.xml
  app/src/main/res/layout/fragment_time_machine_chat3.xml
  app/src/main/res/layout/fragment_time_machine_chat4.xml
  app/src/main/res/layout/fragment_time_machine_lottie.xml
Labels: feature 🚀, 승현 🛵

#92 [FEATURE] 서버 통신 관련 작업
  app/src/main/java/co/kr/deartoday/data/ServiceCreator.kt
  app/src/main/java/co/kr/deartoday/data/service/DeartodayService.kt
  app/src/main/java/co/kr/deartoday/data/sharedpreferences/DearTodaySharedPreferences.kt
  app/src/main/java/co/kr/deartoday/presentation/adapter/TapeAdapter.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timetravel/TimeTravelActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/viewmodel/TimeTravelViewModel.kt
Labels: feature 🚀, 우형 🍩

#96 [FEATURE] 과거 나와의 대화 방 애니메이션 구현
  app/build.gradle
  app/src/main/java/co/kr/deartoday/data/ServiceCreator.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat1Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat2Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat3Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat4Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat5Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineLottieFragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachinePastRoomFragment.kt
  app/src/main/java/co/kr/deartoday/util/AnimationUtil.kt
  app/src/main/res/layout/fragment_time_machine_chat1.xml
  app/src/main/res/layout/fragment_time_machine_chat2.xml
  app/src/main/res/layout/fragment_time_machine_chat3.xml
  app/src/main/res/layout/fragment_time_machine_chat4.xml
  app/src/main/res/layout/fragment_time_machine_chat5.xml
  app/src/main/res/layout/fragment_time_machine_lottie.xml
  app/src/main/res/layout/fragment_time_machine_past_room.xml
Labels: feature 🚀, 승현 🛵

#100 [FEATURE] DI 기초작업 세팅
  app/build.gradle
  app/src/main/java/co/kr/deartoday/data/interceptor/AuthInterceptor.kt
  app/src/main/java/co/kr/deartoday/data/sharedpreferences/DearTodaySharedPreferences.kt
  app/src/main/java/co/kr/deartoday/di/SingletonModule.kt
  build.gradle
Labels: feature 🚀, 승현 🛵

#98 [FEATURE] 메시지 상세 확인 뷰 서버 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/deartoday/data/ServiceCreator.kt
  app/src/main/java/co/kr/deartoday/data/model/response/MessageBoxResponse.kt
  app/src/main/java/co/kr/deartoday/data/model/response/ResponseMessageBox.kt
  app/src/main/java/co/kr/deartoday/data/service/DeartodayService.kt
  app/src/main/java/co/kr/deartoday/data/service/MessageBoxService.kt
  app/src/main/java/co/kr/deartoday/presentation/adapter/MessageBoxAdapter.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/messagebox/MessageBoxActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding10Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding11Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding1Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding2Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding3Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding4Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding5Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding6Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding7Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding8Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding9Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/viewmodel/MessageBoxViewModel.kt
  app/src/main/res/layout/activity_message_box.xml
  app/src/main/res/layout/item_message_box_list.xml
Labels: feature 🚀, 유리 ☁️

#103 [FEATURE] 스플래시 구현
  app/src/main/AndroidManifest.xml
  app/src/main/assets/splash.json
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/DeartodaySplashActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding11Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding1Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding4Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding5Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding7Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding8Fragment.kt
  app/src/main/res/layout/activity_deartoday_splash.xml
  app/src/main/res/values/strings.xml
Labels: feature 🚀, chore 🏗, 유리 ☁️

#108 [FEATURE] 시간여행 가상공간 - 특정 연도, 사진 가져오기 API 연결
  app/src/main/java/co/kr/deartoday/data/model/response/timemachine/PastImages.kt
  app/src/main/java/co/kr/deartoday/data/model/response/timemachine/PastPhotos.kt
  app/src/main/java/co/kr/deartoday/data/repository/TimeMachineRepositoryImpl.kt
  app/src/main/java/co/kr/deartoday/data/service/TimeMachineService.kt
  app/src/main/java/co/kr/deartoday/di/TimeMachineModule.kt
  app/src/main/java/co/kr/deartoday/domain/repository/timemachine/TimeMachineRepository.kt
  app/src/main/java/co/kr/deartoday/presentation/adapter/PastImageAdapter.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat1Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat2Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat3Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat4Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat5Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineImagePickerFragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineLottieFragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachinePastRoomFragment.kt
  app/src/main/java/co/kr/deartoday/presentation/viewmodel/TimeMachineViewModel.kt
  app/src/main/res/layout/item_past_photo.xml
Labels: feature 🚀, 승현 🛵

#115 [FEATURE] 과거 나와의 대화 방 상태 관리
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat1Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat2Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat3Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat4Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat5Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/viewmodel/timemachine/TimeMachineViewModel.kt
  app/src/main/java/co/kr/deartoday/util/ViewExtension.kt
  app/src/main/res/layout/fragment_time_machine_chat4.xml
Labels: feature 🚀, 승현 🛵

#116 [FEATURE] 시간 여행 가상공간 - 과거사진, 날짜, 제목 + 질문, 대답 쓰기 API 연결
  app/src/main/java/co/kr/deartoday/data/model/response/MultipartResponse.kt
  app/src/main/java/co/kr/deartoday/data/service/timemachine/TimeMachineService.kt
  app/src/main/java/co/kr/deartoday/di/TimeMachineModule.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat5Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/usecase/TimeMachineUseCase.kt
  app/src/main/java/co/kr/deartoday/presentation/viewmodel/timemachine/TimeMachineViewModel.kt
Labels: feature 🚀, 승현 🛵

#110 [FIX] 스플래시 및 온보딩 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding4Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/splash/DeartodaySplashActivity.kt
  app/src/main/res/drawable-mdpi/switch_blue.xml
  app/src/main/res/layout/activity_deartoday_splash.xml
Labels: bug 🐛, chore 🏗, 유리 ☁️

#118 [FEATURE] 설정 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/deartoday/data/sharedpreferences/DearTodaySharedPreferences.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/main/MainActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/setting/SettingActivity.kt
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature 🚀, 유리 ☁️

#122 [Feature] 시간 여행 서벼 연동 / 인터셉터 긴급 구현
  app/src/main/java/co/kr/deartoday/data/ServiceCreator.kt
  app/src/main/java/co/kr/deartoday/presentation/adapter/TapeAdapter.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timetravel/TimeTravelActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/viewmodel/SignInViewModel.kt
  app/src/main/java/co/kr/deartoday/presentation/viewmodel/TimeTravelViewModel.kt
  app/src/main/res/layout/item_time_travel.xml
Labels: feature 🚀, 우형 🍩

#121 [CHORE] SETTING 뷰 라인 정리
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable-mdpi/switch_blue.xml
  app/src/main/res/values/themes.xml
Labels: chore 🏗, 유리 ☁️

#125 [FEATURE] 메시지 확인하기 Empty View
  app/src/main/java/co/kr/deartoday/presentation/ui/messagebox/MessageBoxActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/viewmodel/MessageBoxViewModel.kt
  app/src/main/res/layout/activity_message_box.xml
Labels: feature 🚀, 유리 ☁️

#128 [FEATUER] 시간여행 뷰 서버 연동
  app/src/main/java/co/kr/deartoday/data/service/TapeService.kt
  app/src/main/java/co/kr/deartoday/presentation/adapter/TapeAdapter.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timetravel/TimeTravelActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timetravel/TimeTravelDetailActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/viewmodel/SignInViewModel.kt
  app/src/main/java/co/kr/deartoday/presentation/viewmodel/timetravel/TimeTravelDetailViewModel.kt
  app/src/main/java/co/kr/deartoday/presentation/viewmodel/timetravel/TimeTravelViewModel.kt
  app/src/main/java/co/kr/deartoday/util/BreakAllTextView.kt
  app/src/main/res/layout/activity_time_travel.xml
  app/src/main/res/layout/activity_time_travel_detail.xml
  app/src/main/res/layout/item_time_travel.xml
Labels: feature 🚀, 우형 🍩

#127 [FEATURE] 메시지 확인 뷰 API 변경
  app/src/main/java/co/kr/deartoday/data/model/response/MessageBoxResponse.kt
  app/src/main/java/co/kr/deartoday/data/service/MessageBoxService.kt
  app/src/main/java/co/kr/deartoday/presentation/adapter/MessageBoxAdapter.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/messagebox/MessageBoxActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/viewmodel/MessageBoxViewModel.kt
  app/src/main/res/drawable-hdpi/soundon_messagebox_aos.png
  app/src/main/res/drawable-mdpi/soundon_messagebox_aos.png
  app/src/main/res/drawable-xhdpi/soundon_messagebox_aos.png
  app/src/main/res/drawable-xxhdpi/soundon_messagebox_aos.png
  app/src/main/res/drawable-xxxhdpi/soundon_messagebox_aos.png
  app/src/main/res/layout/activity_deartoday_splash.xml
  app/src/main/res/layout/activity_message_box.xml
Labels: feature 🚀, 유리 ☁️

#130 [FEATURE] 설정뷰 구현 / 화면전환 효과 구현 및 적용
  app/src/main/java/co/kr/deartoday/data/ServiceCreator.kt
  app/src/main/java/co/kr/deartoday/data/service/AuthService.kt
  app/src/main/java/co/kr/deartoday/presentation/adapter/MessageBoxAdapter.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/main/MainActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/main/MainRightFragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/messagebox/MessageBoxActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding10Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding11Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding2Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding3Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding4Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding5Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding6Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding7Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding8Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding9Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/setting/SettingActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineImagePickerFragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timetravel/TimeTravelActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/viewmodel/setting/SettingViewModel.kt
  app/src/main/java/co/kr/deartoday/presentation/viewmodel/timetravel/TimeTravelViewModel.kt
  app/src/main/res/anim/not_move.xml
  app/src/main/res/anim/right_in.xml
  app/src/main/res/anim/right_out.xml
  app/src/main/res/layout/activity_time_travel.xml
Labels: feature 🚀, chore 🏗, 유리 ☁️, 우형 🍩

#133 [FEATURE] 과거 나와의 대화 방 리액션 추가
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat4Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat5Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/viewmodel/timemachine/TimeMachineViewModel.kt
Labels: feature 🚀, 승현 🛵

#132 [FEATURE] Splash Finish 구현
  app/src/main/java/co/kr/deartoday/presentation/ui/main/MainActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding11Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/OnboardingActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/signin/SignInActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/splash/DeartodaySplashActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timetravel/TimeTravelActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timetravel/TimeTravelDetailActivity.kt
  app/src/main/res/values/strings.xml
Labels: feature 🚀, 유리 ☁️

#137 [FEATURE] FCM 푸시 알림 셋팅
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/deartoday/config/DeartodayMessagingService.kt
  app/src/main/java/co/kr/deartoday/data/sharedpreferences/DearTodaySharedPreferences.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/signin/SignInActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/viewmodel/SignInViewModel.kt
  app/src/main/res/values/strings.xml
  build.gradle
Labels: feature 🚀, 승현 🛵

#136 [FIX] Design QA 변경사항 반영 : 유리
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding11Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding5Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding7Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/onboarding/Onboarding8Fragment.kt
  app/src/main/res/drawable-hdpi/bg_letter.png
  app/src/main/res/drawable-mdpi/bg_letter.png
  app/src/main/res/drawable-xhdpi/bg_letter.png
  app/src/main/res/drawable-xxhdpi/bg_letter.png
  app/src/main/res/drawable-xxxhdpi/bg_letter.png
  app/src/main/res/drawable/ic_bg_letter.xml
  app/src/main/res/layout/fragment_main_left.xml
  app/src/main/res/layout/fragment_main_right.xml
  app/src/main/res/layout/fragment_onboarding1.xml
  app/src/main/res/layout/fragment_onboarding11.xml
  app/src/main/res/layout/fragment_onboarding2.xml
  app/src/main/res/layout/fragment_onboarding4.xml
  app/src/main/res/layout/fragment_onboarding5.xml
  app/src/main/res/layout/fragment_onboarding6.xml
  app/src/main/res/layout/fragment_onboarding7.xml
  app/src/main/res/layout/fragment_onboarding8.xml
  app/src/main/res/layout/fragment_onboarding9.xml
Labels: chore 🏗, 유리 ☁️

#140 [FIX] 디자인 QA + 기능 QA
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat1Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat3Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat4Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat5Fragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineImagePickerFragment.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachinePastRoomFragment.kt
  app/src/main/java/co/kr/deartoday/presentation/viewmodel/timemachine/TimeMachineViewModel.kt
  app/src/main/res/layout/fragment_time_machine_chat1.xml
  app/src/main/res/layout/fragment_time_machine_chat4.xml
Labels: feature 🚀, 승현 🛵

#141 [FIX] QA - 마지막 멘트 변경
  app/src/main/java/co/kr/deartoday/presentation/ui/timetravel/TimeTravelDetailActivity.kt
Labels: chore 🏗, 우형 🍩

#143 [FIX] #142 - ivImage.clipToOutline 속성 코드단에서 초기화
  app/src/main/java/co/kr/deartoday/presentation/ui/timemachine/TimeMachineChat4Fragment.kt
Labels: bug 🐛, 우형 🍩

#145 [FEATURE] DI 적용
  app/src/main/AndroidManifest.xml
  app/src/main/java/co/kr/deartoday/data/ServiceCreator.kt
  app/src/main/java/co/kr/deartoday/data/model/request/auth/LoginRequest.kt
  app/src/main/java/co/kr/deartoday/data/model/request/auth/LogoutRequest.kt
  app/src/main/java/co/kr/deartoday/data/service/AuthService.kt
  app/src/main/java/co/kr/deartoday/data/service/auth/AuthService.kt
  app/src/main/java/co/kr/deartoday/data/service/messagebox/MessageBoxService.kt
  app/src/main/java/co/kr/deartoday/data/service/tape/TapeService.kt
  app/src/main/java/co/kr/deartoday/di/ServiceModule.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/messagebox/MessageBoxActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/setting/SettingActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/signin/SignInActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timetravel/TimeTravelActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/ui/timetravel/TimeTravelDetailActivity.kt
  app/src/main/java/co/kr/deartoday/presentation/viewmodel/messagebox/MessageBoxViewModel.kt
  app/src/main/java/co/kr/deartoday/presentation/viewmodel/setting/SettingViewModel.kt
  app/src/main/java/co/kr/deartoday/presentation/viewmodel/signin/SignInViewModel.kt
  app/src/main/java/co/kr/deartoday/presentation/viewmodel/timetravel/TimeTravelDetailViewModel.kt
  app/src/main/java/co/kr/deartoday/presentation/viewmodel/timetravel/TimeTravelViewModel.kt
  app/src/main/res/layout/activity_message_box.xml
Labels: feature 🚀, 승현 🛵
